version: "3.9"  

services:
  twingate:
    image: twingate/connector:1
    container_name: twingate-tactful-rabbit
    restart: unless-stopped
    sysctls:
      - net.ipv4.ping_group_range="0 2147483647"
    environment:
      - TWINGATE_NETWORK=themalechouse 
      - TWINGATE_LABEL_HOSTNAME="`hostname`"
      - TWINGATE_LABEL_DEPLOYED_BY="docker"
    secrets:
      - TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN
    pull_always: true

secrets:
  TWINGATE_ACCESS_TOKEN:
    external: true
  TWINGATE_REFRESH_TOKEN:
    external: true

