# ref: https://hub.docker.com/r/itzg/minecraft-server/
image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: Always
  pullSecret: ""

replicaCount: 1

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 8G
    cpu: 4000m # 4 Cores

lifecycle:
  postStart: []
  preStop: []

# If true the workload is defined as a StatefulSet instead of a Deployment.
# Make sure to also update the strategyType!
# All configuration options for the Deployment (e.g. annotations) are used for the StatefulSet.
# Regarding persistence: When an existing PVC is provided it will be shared between all Pods.
# Otherwise the PVC configuration is used as a template to create PVCs for each replica.
workloadAsStatefulSet: true

# upgrade strategy type, depending on workload type:
# - for Deployment sets strategy: Recreate or RollingUpdate
# - for StatefulSet sets updateStrategy: OnDelete or RollingUpdate
strategyType: RollingUpdate

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  runAsNonRoot: true
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

# Most of these map to environment variables. See Minecraft for details:
# https://hub.docker.com/r/itzg/minecraft-server/
livenessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  command:
    - mc-health
  enabled: false
  failureThreshold: 30
  periodSeconds: 10

initContainers: []

sidecarContainers: []

extraVolumes: []

extraDeploy: []

extraPodSpec: {}

minecraftServer:
  # This must be overridden, since we can't accept this for the user.
  eula: "TRUE"
  # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
  version: "1.21.5" 
  ## The type of Minecraft server to run, check for related settings below
  ## Common types: "VANILLA", "FABRIC", "FORGE", "SPIGOT", "BUKKIT", "PAPER",
  ## "FTBA", "SPONGEVANILLA", "AUTO_CURSEFORGE", "MODRINTH"
  ## ref: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
  type: "MODRINTH"
  # If type is set to FORGE, this sets the version; this is ignored if forgeInstallerUrl is set
  forgeVersion:
  # If type is set to FORGE, this sets the URL to download the Forge installer
  forgeInstallerUrl:
  # If type is set to SPONGEVANILLA, this sets the version
  spongeVersion:
  # If type is set to BUKKIT, this sets the URL to download the Bukkit package
  bukkitDownloadUrl:
  # If type is set to SPIGOT, this sets the URL to download the Spigot package
  spigotDownloadUrl:
  # If type is set to PAPER, this sets the URL to download the PaperSpigot package
  paperDownloadUrl:
  # If type is set to FTBA, this sets the modpack to run
  ftbModpackId:
  # If type is set to FTBA and a modpack is set, this sets the version to run
  ftbModpackVersionId:
  # If type is set to CURSEFORGE, this sets the server mod to run. Can also provide url to curseforge package.
  cfServerMod:
  ## If type is set to FABRIC, this sets the version of fabric server launcher
  ## to use. Defaults to latest available for minecraftServer.version.
  ##
  ## For a custom launcher, see: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/fabric/
  fabricLauncherVersion:
  ## If type is set to FABRIC, this sets the version of fabric-loader to use.
  ## Defaults to latest available for minecraftServer.version.
  fabricLoaderVersion:
  # Set to true if running Feed The Beast and get an error like "unable to launch forgemodloader"
  ftbLegacyJavaFixer: default
  # One of: peaceful, easy, normal, and hard
  difficulty: easy
  # A comma-separated list of player names to whitelist.
  whitelist:
  # A comma-separated list of player names who should be admins.
  ops:
  # A server icon URL for server listings. Auto-scaled and transcoded.
  icon:
  # Max connected players.
  maxPlayers: default
  # This sets the maximum possible size in blocks, expressed as a radius, that the world border can obtain.
  maxWorldSize: default
  # Allows players to travel to the Nether.
  allowNether: default
  # Allows server to announce when a player gets an achievement.
  announcePlayerAchievements: default
  # Enables command blocks.
  enableCommandBlock: default
  # If true, players will always join in the default gameMode even if they were previously set to something else.
  forcegameMode: default
  # Defines whether structures (such as villages) will be generated.
  generateStructures: default
  # If set to true, players will be set to spectator mode if they die.
  hardcore: default
  # The maximum height in which building is allowed.
  maxBuildHeight: default
  # The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message. -1 disables this entirely.
  maxTickTime: default
  # Determines if animals will be able to spawn.
  spawnAnimals: default
  # Determines if monsters will be spawned.
  spawnMonsters: default
  # Determines if villagers will be spawned.
  spawnNPCs: default
  # Sets the area that non-ops can not edit (0 to disable)
  spawnProtection: default
  # Max view distance (in chunks).
  viewDistance: default
  # Define this if you want a specific map generation seed.
  levelSeed:
  # One of: creative, survival, adventure, spectator
  gameMode: survival
  # Message of the Day
  motd: "Welcome to the GoonLag MC Server"
  # If true, enable player-vs-player damage.
  pvp: default
  # One of: DEFAULT, FLAT, LARGEBIOMES, AMPLIFIED, CUSTOMIZED
  levelType: DEFAULT
  # When levelType == FLAT or CUSTOMIZED, this can be used to further customize map generation.
  # ref: https://hub.docker.com/r/itzg/minecraft-server/
  generatorSettings:
  worldSaveName: world
  # If set, this URL will be downloaded at startup and used as a starting point
  downloadWorldUrl:
  # force re-download of server file
  forceReDownload: false
  # If set, the modpack at this URL will be downloaded at startup
  downloadModpackUrl:
  # If true, old versions of downloaded mods will be replaced with new ones from downloadModpackUrl
  removeOldMods: false
  # A list of VanillaTweaks Share Codes to download. (https://vanillatweaks.net/share#wUq1iz => "wUq1iz")
  vanillaTweaksShareCodes: []
  # Optional URI to a resource pack. The player may choose to use it.
  resourcePackUrl:
  # Optional SHA-1 digest of the resource pack, in lowercase hexadecimal.
  # It is recommended to specify this, because it is used to verify the integrity of the resource pack.
  resourcePackSha:
  # When true, players will be prompted for a response and will be disconnected if they decline the required pack
  resourcePackEnforce: false
  # Check accounts against Minecraft account service.
  onlineMode: default
  # Require public key to be signed by Mojang to join
  enforceSecureProfile: default
  # If you adjust this, you may need to adjust resources.requests above to match.
  memory: 1024M
  # General JVM options to be passed to the Minecraft server invocation
  jvmOpts: ""
  # Options like -X that need to proceed general JVM options
  jvmXXOpts: ""
  overrideServerProperties: default
  # DEPRECATED: use top-level rconServiceAnnotations instead
  serviceAnnotations: {}
  serviceType: NodePort
  ## Set the port used if the serviceType is NodePort
  nodePort: 30013
  # Set the external port of the service, usefull when using the LoadBalancer service type
  servicePort: 25565
  clusterIP:
  loadBalancerClass:
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster
  externalIPs:

  # List with URLs and paths to jar files, additionally may be a directory with jars
  # This works for both mods and plugins depending on server type
  modUrls: []
  pluginUrls: []

  # A list of Spigot resources/plugins IDs to download.
  spigetResources: []

  # Additional service specs to be defined
  extraServiceSpec: {}

  # Configuration for MODRINTH_PROJECT (modpack) type
  # Note: This is different from modrinth.projects which is for individual mods
  modrinthProject: "vanilla-perfected"
  
  # Optional: Specify a specific version
  # modrinthProjectVersion: "1.0.0+1.21.5"
  
  # A list of Modrinth project slugs with optional version after colon
  # This is used when installing individual mods, not for modpacks
  modrinth:
    # projects: [1ocGzRHv]
    # Specifies whether to download Modrinth dependencies. The allowed values are: none, required, optional
    # downloadDependencies: optional
    # # The version type is used to determine the newest version to use from each project. The allowed values are: release, beta, alpha
    # allowedVersionType: release

  # Config for AUTO_CURSEFORGE server type
  autoCurseForge:
    # CurseForge API key obtained from developer console
    apiKey:
      key: "CHANGEME!"
      existingSecret: ""
      secretKey: cf-api-key
    # Link to modpack in general or a specific file
    # NOTE: In case of specific file - do not point at server file
    pageUrl: ""
    # Unique id of modpack, can be used instead of url
    slug: ""
    # Id used to specify which exact modpack file needs to be downloaded
    # NOTE: Do not use server file id
    fileId: ""
    # Less restrictive way of specifying modpack version, uses substring match
    filenameMatcher: ""
    # List of project slugs or IDs to be excluded from modpack, useful if mod is incorrectly marked as server side
    excludeMods: []
    # List of project slugs or IDs to be included in modpack, useful if mod is incorrectly marked as client side only
    includeMods: []
    # Path to file with rules for including and excluding mods. If null - use bundled file, if empty - disable it
    excludeIncludeFile: null
    # Reevaluate exclude and include rules
    forceSynchronize: false
    # Can be set to either WORLD_FILE or OVERRIDES to specify where to get LEVEL
    setLevelFrom: ""
    # Sets limit to how many mods can be downloaded in parallel
    parallelDownloads: 4
    # Set to skip files in modpack "overrides" folder that would replace existing files
    # NOTE: World data is always skipped if present
    overridesSkipExisting: false

  rcon:
    # If you enable this, make SURE to change your password below.
    enabled: false
    # By default, the container will generate a random password at startup
    # to ensure internal RCON tooling, including a backup container,
    # can be used, but the password is secure.
    withGeneratedPassword: false
    port: 25575
    password: "CHANGEME!"
    existingSecret:
    secretKey: rcon-password
    serviceType: ClusterIP
    ## Set the external port if the rcon serviceType is NodePort
    nodePort:
    clusterIP:
    loadBalancerClass:
    loadBalancerIP:
    # loadBalancerSourceRanges: []
    ## Set the externalTrafficPolicy in the Service to either Cluster or Local
    # externalTrafficPolicy: Cluster

  ## set this to false to not have colorized logs
  tty: true

  extraPorts:
    []

  query:
    # If you enable this, your server will be "published" to Gamespy
    enabled: false
    port: 25565

## Additional minecraft container environment variables
## Values can be either variable values or `valueFrom` yaml
##
extraEnv:
  # Required when using TYPE: MODRINTH
  MODRINTH_MODPACK: "vanilla-perfected"
  # MODRINTH_MODPACK_VERSION: "1.0.0+1.21.5"
  # Disable autopause to keep the server always running
  ENABLE_AUTOPAUSE: "FALSE"

## Additional environment variables to add to the minecraft container from
## ConfigMaps and Secrets
##
envFrom: []

persistence:
  labels: {}
  annotations: {}
  ## specify an alternative volume to be mounted to /data instead of datadir.
  # altDataVolumeName: ""
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: true
    storageClass: "local-path"
    size: 20Gi
    accessModes:
      - ReadWriteOnce
    ## specify a subpath in the volume where the data is. Useful when sharing volumes with other apps.
    # subPath: /path/to/dataDir

podAnnotations: {}
podLabels: {}

deploymentAnnotations: {}
deploymentLabels: {}

serviceAnnotations: {}
serviceLabels: {}

rconServiceAnnotations: {}
rconServiceLabels: {}

mcbackup:
  enabled: false