apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory-chart.fullname". }}
  labels:
    {{- include "satisfactory-chart.labels". | nindent 4 }}
spec:
  type: {{.Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{.Values.service.port }}
      targetPort: satisfactory-tcp
      protocol: TCP
      name: satisfactory-tcp
    - port: {{.Values.service.port }}
      targetPort: satisfactory-udp
      protocol: UDP
      name: satisfactory-udp
  selector:
    {{- include "satisfactory-chart.selectorLabels". | nindent 4 }}