apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
    - name: game-udp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
    - name: game-tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}c
    