apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: "game-udp"
      port: 7777
      protocol: TCP
      targetPort: 7777
    - name: "game-tcp"
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: "messaging-tcp"
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: "messaging-udp"
      port: 8888
      protocol: UDP
      targetPort: 8888
  selector:
    app: {{ .Chart.Name }}