apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-restart
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 3 * * *" # 3:00 AM every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Chart.Name }}-restarter
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl delete pod {{ .Chart.Name }}-0 -n {{ .Values.namespace }}
          restartPolicy: OnFailure 