apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-restarter
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restarter
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-restarter-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restarter
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-restarter
  namespace: {{ .Values.namespace }} 