apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName:  {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
    spec:
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          env:
            - name: DEBUG
              value: "false"
            - name: MAXPLAYERS
              value: "8"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SKIPUPDATE
              value: "false"
            - name: STEAMBETA
              value: "true"
          ports:
            - name: "api"
              containerPort: 7777
              protocol: TCP
            - name: "game"
              containerPort: 7777
              protocol: UDP
            - name: "messaging"
              containerPort: 8888
              protocol: TCP
            - name: "messaging-udp"
              containerPort: 8888
              protocol: UDP
          volumeMounts:
            - name: game-data
              mountPath: /config
      volumes:
        - name: game-data
          persistentVolumeClaim:
            claimName: satisfactory-files