apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-game-pv-claim
spec:
  accessModes:
    - ReadWriteMany # Or ReadWriteMany if your game server supports it
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  storageClassName: {{ .Values.storageClassName }}