# Default values for longhorn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  ui:
    type: ClusterIP

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain

defaultSettings:
  backupTarget: ""
  backupTargetCredentialSecret: ""
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn/
  defaultReplicaCount: 2
  guaranteedEngineManagerCPU: 0.1
  guaranteedReplicaManagerCPU: 0.1
