service:
  ui:
    type: NodePort
    nodePort: 30080

longhornUI:
  replicas: 1
  nodeSelector:
    node-role.kubernetes.io/worker: "true"

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain

defaultSettings:
  backupTarget: ""
  backupTargetCredentialSecret: ""
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn/
  defaultReplicaCount: 2
  guaranteedEngineManagerCPU: 0.1
  guaranteedReplicaManagerCPU: 0.1
